<a href="https://colab.research.google.com/github/nehansa2003/NLP_project/blob/main/Review_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
import pandas as pd
import numpy as np
import re
import os

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
file_path = '/content/drive/MyDrive/datasets/all_game_reviews.csv'
df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (101862, 10)

,game_id,game_name,game_url,review_id,author,outlet,score,date,review_text,review_url
0,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,f66e621c-15bb-4687-bdf3-3b57627806be,Riley Little,Game Rant,5 stars,26-Oct-17,Super Mario Odyssey is a spectacular return to...,https://gamerant.com/super-mario-odyssey-review/
1,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,ea35e02a-7de8-48dd-ab13-ee0f7965b318,Ryan McCaffrey,IGN,10 / 10.0,26-Oct-17,Mario's games have been around for almost as l...,http://www.ign.com/articles/2017/10/26/super-m...
2,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,13bf1797-c39f-46ce-a066-fc3844accb6f,Oli Welsh,Eurogamer,Essential,26-Oct-17,One of the most daring and influential game de...,http://www.eurogamer.net/articles/2017-10-26-s...
3,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,2bfa5c9e-651a-4ee2-a870-f9828e4c668d,Sam Loveridge,GamesRadar+,5 stars,26-Oct-17,Super Mario Odyssey successfully brings the se...,http://www.gamesradar.com/super-mario-odyssey-...
4,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,04c62a12-ba03-4bcc-8623-d7b9b52b2f88,Andrew Reiner,Game Informer,9.8 / 10.0,26-Oct-17,With hundreds of moons to collect and a dizzyi...,http://www.gameinformer.com/games/super_mario_...

In [5]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset info:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

print("\nFirst 5 reviews:")
display(df.head())

Rows: 101862
Columns: 10

Column names:
['game_id', 'game_name', 'game_url', 'review_id', 'author', 'outlet', 'score', 'date', 'review_text', 'review_url']

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101862 entries, 0 to 101861
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      101862 non-null  int64
 1   game_name    101862 non-null  object
 2   game_url     101862 non-null  object
 3   review_id    101862 non-null  object
 4   author       93170 non-null   object
 5   outlet       101862 non-null  object
 6   score        98288 non-null   object
 7   date         101862 non-null  object
 8   review_text  100081 non-null  object
 9   review_url   95162 non-null   object
dtypes: int64(1), object(9)
memory usage: 7.8+ MB

Missing values:
game_id           0
game_name         0
game_url          0
review_id         0
author         8692
outlet            0
score          3574
date              0
review_text    1781
review_url     6700
dtype: int64

First 5 reviews:

,game_id,game_name,game_url,review_id,author,outlet,score,date,review_text,review_url
0,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,f66e621c-15bb-4687-bdf3-3b57627806be,Riley Little,Game Rant,5 stars,26-Oct-17,Super Mario Odyssey is a spectacular return to...,https://gamerant.com/super-mario-odyssey-review/
1,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,ea35e02a-7de8-48dd-ab13-ee0f7965b318,Ryan McCaffrey,IGN,10 / 10.0,26-Oct-17,Mario's games have been around for almost as l...,http://www.ign.com/articles/2017/10/26/super-m...
2,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,13bf1797-c39f-46ce-a066-fc3844accb6f,Oli Welsh,Eurogamer,Essential,26-Oct-17,One of the most daring and influential game de...,http://www.eurogamer.net/articles/2017-10-26-s...
3,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,2bfa5c9e-651a-4ee2-a870-f9828e4c668d,Sam Loveridge,GamesRadar+,5 stars,26-Oct-17,Super Mario Odyssey successfully brings the se...,http://www.gamesradar.com/super-mario-odyssey-...
4,1,Super Mario Odyssey,https://opencritic.com/game/4504/super-mario-o...,04c62a12-ba03-4bcc-8623-d7b9b52b2f88,Andrew Reiner,Game Informer,9.8 / 10.0,26-Oct-17,With hundreds of moons to collect and a dizzyi...,http://www.gameinformer.com/games/super_mario_...

Make a copy

In [6]:
data = df.copy()

print("Working dataset shape:", data.shape)

Working dataset shape: (101862, 10)

Check duplicates

In [7]:
print("Duplicate review IDs:", data['review_id'].duplicated().sum())

print("Duplicate review texts:", data['review_text'].duplicated().sum())

Duplicate review IDs: 0
Duplicate review texts: 2387

Remove Duplicate review_ids

In [8]:
data = data.drop_duplicates(subset='review_id', keep='first').reset_index(drop=True)

print("Shape after removing duplicate review IDs:", data.shape)

Shape after removing duplicate review IDs: (101862, 10)

Handle missing review text

In [9]:
before = len(data)

data = data.dropna(subset=['review_text']).copy()

data = data[data['review_text'].str.strip() != ''].copy()

data = data.reset_index(drop=True)

print("Rows before:", before)
print("Rows after:", len(data))
print("Reviews removed:", before - len(data))

Rows before: 101862
Rows after: 100081
Reviews removed: 1781

Clean the review text

In [10]:
def clean_text(text):
    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', ' ', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Keep letters, numbers and basic punctuation
    text = re.sub(r'[^a-z0-9\s.,!?\'-]', ' ', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text


data['clean_review_text'] = data['review_text'].apply(clean_text)

display(
    data[['review_text', 'clean_review_text']].head(10)
)

,review_text,clean_review_text
0,Super Mario Odyssey is a spectacular return to...,super mario odyssey is a spectacular return to...
1,Mario's games have been around for almost as l...,mario's games have been around for almost as l...
2,One of the most daring and influential game de...,one of the most daring and influential game de...
3,Super Mario Odyssey successfully brings the se...,super mario odyssey successfully brings the se...
4,With hundreds of moons to collect and a dizzyi...,with hundreds of moons to collect and a dizzyi...
5,"For a character nearing 40 years old, it's ama...","for a character nearing 40 years old, it's ama..."
6,Super Mario Odyssey is a massive and magnifice...,super mario odyssey is a massive and magnifice...
7,The soul of Super Mario 64 is alive and well i...,the soul of super mario 64 is alive and well i...
8,Every element gelled so well that I was simply...,every element gelled so well that i was simply...
9,"Odyssey is the best Mario game in many, many y...","odyssey is the best mario game in many, many y..."

Remove extremely short reviews

In [11]:
data['word_count'] = data['clean_review_text'].str.split().str.len()

print(data['word_count'].describe())

count    100081.000000
mean         52.575884
std          33.135410
min           0.000000
25%          27.000000
50%          45.000000
75%          70.000000
max         828.000000
Name: word_count, dtype: float64

In [12]:
data = data[data['word_count'] >= 3].copy()

data.reset_index(drop=True, inplace=True)

print("Dataset after text filtering:", data.shape)

Dataset after text filtering: (100027, 12)

Normalize the score column

In [13]:
print(data['score'].value_counts(dropna=False).head(30))

score
9 / 10.0       13281
8 / 10.0        9046
5 stars         8733
8.5 / 10.0      7963
10-Aug          5270
4 stars         5058
10-Sep          4950
9.5 / 10.0      4340
NaN             3217
10 / 10.0       2760
7.5 / 10.0      2243
7 / 10.0        2008
10-Jul          1745
90 / 100        1724
4.5 / 5.0       1424
4 / 5.0         1318
85 / 100        1147
8.8 / 10.0      1111
80 / 100        1053
10-Oct           919
Recommended      831
95 / 100         627
8.3 / 10.0       584
10 stars         545
8.7 / 10.0       521
9.3 / 10.0       497
8.2 / 10.0       494
9.2 / 10.0       493
5 / 5.0          478
8.6 / 10.0       433
Name: count, dtype: int64

In [14]:
def normalize_score(score):
    if pd.isna(score):
        return np.nan

    score = str(score).strip().lower()

    # "10 / 10.0", "9.8 / 10.0", etc.
    match = re.search(r'(\d+(?:\.\d+)?)\s*/\s*(\d+(?:\.\d+)?)', score)

    if match:
        value = float(match.group(1))
        maximum = float(match.group(2))

        if maximum > 0:
            return (value / maximum) * 100

    # "5 stars"
    match = re.search(r'(\d+(?:\.\d+)?)\s*stars?', score)

    if match:
        value = float(match.group(1))
        return (value / 5) * 100

    # Pure numeric value
    if re.fullmatch(r'\d+(?:\.\d+)?', score):
        value = float(score)

        if value <= 10:
            return value * 10

        return value

    # Text-based score
    if 'essential' in score:
        return 100

    return np.nan


data['score_normalized'] = data['score'].apply(normalize_score)

display(
    data[['score', 'score_normalized']].head(30)
)

         score  score_normalized
0      5 stars             100.0
1    10 / 10.0             100.0
2    Essential             100.0
3      5 stars             100.0
4   9.8 / 10.0              98.0
5   9.5 / 10.0              95.0
6       10-Oct               NaN
7      5 stars             100.0
8          NaN               NaN
9          NaN               NaN
10         NaN               NaN
11     5 / 5.0             100.0
12      10-Oct               NaN
13   100 / 100             100.0
14   10 / 10.0             100.0
15      10-Oct               NaN
16  9.5 / 10.0              95.0
17   10 / 10.0             100.0
18  9.7 / 10.0              97.0
19     5 stars             100.0
20      10-Sep               NaN
21         NaN               NaN
22  9.5 / 10.0              95.0
23  9.5 / 10.0              95.0
24   10 / 10.0             100.0
25      10-Oct               NaN
26      10-Oct               NaN
27    98 / 100              98.0
28     5 stars             100.0
29    9 / 10.0              90.0

Create sentiment labels

In [15]:
def create_sentiment(score):
    if pd.isna(score):
        return np.nan

    if score >= 80:
        return 'positive'
    elif score >= 60:
        return 'neutral'
    else:
        return 'negative'


data['sentiment'] = data['score_normalized'].apply(create_sentiment)

In [16]:
print(data['sentiment'].value_counts(dropna=False))

print("\nPercentage:")
print(
    data['sentiment']
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

sentiment
positive    69865
NaN         21883
neutral      7980
negative      299
Name: count, dtype: int64

Percentage:
sentiment
positive    69.85
NaN         21.88
neutral      7.98
negative     0.30
Name: proportion, dtype: float64

Check the cleaned dataset

In [17]:
print("Final preprocessing shape:", data.shape)

print("\nColumns:")
print(data.columns.tolist())

print("\nMissing values:")
print(data.isnull().sum())

Final preprocessing shape: (100027, 14)

Columns:
['game_id', 'game_name', 'game_url', 'review_id', 'author', 'outlet', 'score', 'date', 'review_text', 'review_url', 'clean_review_text', 'word_count', 'score_normalized', 'sentiment']

Missing values:
game_id                  0
game_name                0
game_url                 0
review_id                0
author                8409
outlet                   0
score                 3217
date                     0
review_text              0
review_url            4926
clean_review_text        0
word_count               0
score_normalized     21883
sentiment            21883
dtype: int64

In [18]:
display(
    data[
        [
            'game_name',
            'score',
            'score_normalized',
            'sentiment',
            'review_text',
            'clean_review_text'
        ]
    ].head(10)
)

,game_name,score,score_normalized,sentiment,review_text,clean_review_text
0,Super Mario Odyssey,5 stars,100.0,positive,Super Mario Odyssey is a spectacular return to...,super mario odyssey is a spectacular return to...
1,Super Mario Odyssey,10 / 10.0,100.0,positive,Mario's games have been around for almost as l...,mario's games have been around for almost as l...
2,Super Mario Odyssey,Essential,100.0,positive,One of the most daring and influential game de...,one of the most daring and influential game de...
3,Super Mario Odyssey,5 stars,100.0,positive,Super Mario Odyssey successfully brings the se...,super mario odyssey successfully brings the se...
4,Super Mario Odyssey,9.8 / 10.0,98.0,positive,With hundreds of moons to collect and a dizzyi...,with hundreds of moons to collect and a dizzyi...
5,Super Mario Odyssey,9.5 / 10.0,95.0,positive,"For a character nearing 40 years old, it's ama...","for a character nearing 40 years old, it's ama..."
6,Super Mario Odyssey,10-Oct,NaN,NaN,Super Mario Odyssey is a massive and magnifice...,super mario odyssey is a massive and magnifice...
7,Super Mario Odyssey,5 stars,100.0,positive,The soul of Super Mario 64 is alive and well i...,the soul of super mario 64 is alive and well i...
8,Super Mario Odyssey,NaN,NaN,NaN,Every element gelled so well that I was simply...,every element gelled so well that i was simply...
9,Super Mario Odyssey,NaN,NaN,NaN,"Odyssey is the best Mario game in many, many y...","odyssey is the best mario game in many, many y..."

Now create the 77.5 / 20 / 2.5 split

In [19]:
games = data['game_name'].dropna().unique()

print("Number of unique games:", len(games))

Number of unique games: 2000

Split the games

In [20]:
from sklearn.model_selection import train_test_split

# First: 77.5% training and 22.5% remaining
train_games, remaining_games = train_test_split(
    games,
    test_size=0.225,
    random_state=42
)

# From remaining 22.5%:
# 20% of total = 88.888...% of remaining
# 2.5% of total = 11.111...% of remaining

test_games, unseen_games = train_test_split(
    remaining_games,
    test_size=0.1111111111,
    random_state=42
)

print("Training games:", len(train_games))
print("Testing games:", len(test_games))
print("Unseen games:", len(unseen_games))

print("\nTotal:", len(train_games) + len(test_games) + len(unseen_games))

Training games: 1550
Testing games: 400
Unseen games: 50

Total: 2000

Create the three datasets

In [21]:
train_df = data[data['game_name'].isin(train_games)].copy()

test_df = data[data['game_name'].isin(test_games)].copy()

unseen_df = data[data['game_name'].isin(unseen_games)].copy()

In [22]:
print("TRAINING")
print(train_df.shape)

print("\nTESTING")
print(test_df.shape)

print("\nUNSEEN")
print(unseen_df.shape)

TRAINING
(77607, 14)

TESTING
(19640, 14)

UNSEEN
(2780, 14)

Verify there is no game overlap

In [23]:
train_set = set(train_games)
test_set = set(test_games)
unseen_set = set(unseen_games)

print("Train ∩ Test:", len(train_set & test_set))
print("Train ∩ Unseen:", len(train_set & unseen_set))
print("Test ∩ Unseen:", len(test_set & unseen_set))

Train ∩ Test: 0
Train ∩ Unseen: 0
Test ∩ Unseen: 0

In [29]:
assert len(train_set & test_set) == 0
assert len(train_set & unseen_set) == 0
assert len(test_set & unseen_set) == 0

print("No game overlap between train, test and unseen datasets.")

No game overlap between train, test and unseen datasets.

Save the processed datasets

In [25]:
output_folder = '/content/drive/MyDrive/NLP_Game_Review_Project'

os.makedirs(output_folder, exist_ok=True)

print("Output folder:", output_folder)

Output folder: /content/drive/MyDrive/NLP_Game_Review_Project

In [26]:
train_path = os.path.join(output_folder, 'train_reviews.csv')
test_path = os.path.join(output_folder, 'test_reviews.csv')
unseen_path = os.path.join(output_folder, 'unseen_reviews.csv')

train_df.to_csv(train_path, index=False)
test_df.to_csv(test_path, index=False)
unseen_df.to_csv(unseen_path, index=False)

print("Files saved successfully!")
print(train_path)
print(test_path)
print(unseen_path)

Files saved successfully!
/content/drive/MyDrive/NLP_Game_Review_Project/train_reviews.csv
/content/drive/MyDrive/NLP_Game_Review_Project/test_reviews.csv
/content/drive/MyDrive/NLP_Game_Review_Project/unseen_reviews.csv

Also save the game lists

In [27]:
pd.DataFrame({'game_name': train_games}).to_csv(
    os.path.join(output_folder, 'train_games.csv'),
    index=False
)

pd.DataFrame({'game_name': test_games}).to_csv(
    os.path.join(output_folder, 'test_games.csv'),
    index=False
)

pd.DataFrame({'game_name': unseen_games}).to_csv(
    os.path.join(output_folder, 'unseen_games.csv'),
    index=False
)

print("Game split files saved.")

Game split files saved.

Final verification

In [28]:
print("=" * 60)
print("GAME REVIEW NLP DATASET")
print("=" * 60)

print(f"Total processed reviews : {len(data):,}")
print(f"Total games             : {data['game_name'].nunique():,}")

print("\nGAME SPLIT")
print("-" * 60)

print(f"Training games : {len(train_games):,} "
      f"({len(train_games)/len(games)*100:.2f}%)")

print(f"Testing games  : {len(test_games):,} "
      f"({len(test_games)/len(games)*100:.2f}%)")

print(f"Unseen games   : {len(unseen_games):,} "
      f"({len(unseen_games)/len(games)*100:.2f}%)")

print("\nREVIEW COUNTS")
print("-" * 60)

print(f"Training reviews : {len(train_df):,}")
print(f"Testing reviews  : {len(test_df):,}")
print(f"Unseen reviews   : {len(unseen_df):,}")

print("\nSENTIMENT")
print("-" * 60)

print(data['sentiment'].value_counts(dropna=False))

print("\n✓ Preprocessing and game-level splitting complete.")

============================================================
GAME REVIEW NLP DATASET
============================================================
Total processed reviews : 100,027
Total games             : 2,000

GAME SPLIT
------------------------------------------------------------
Training games : 1,550 (77.50%)
Testing games  : 400 (20.00%)
Unseen games   : 50 (2.50%)

REVIEW COUNTS
------------------------------------------------------------
Training reviews : 77,607
Testing reviews  : 19,640
Unseen reviews   : 2,780

SENTIMENT
------------------------------------------------------------
sentiment
positive    69865
NaN         21883
neutral      7980
negative      299
Name: count, dtype: int64

✓ Preprocessing and game-level splitting complete.